name: Build images (Call)
# TODO maybe have this somehow reflect the origin? Dunno what's best inside the event.
# or just reflect that it does a release also on release.
# run-name: Build images ${{ startsWith(github.ref, 'refs/tags/v') && 'Release' || 'Snapshot' }}

on:
  pull_request:
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
    # and https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
    # can probably combine with a caller to filter on label following
    # https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label
    types: [opened, synchronize]
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions: write-all # Necessary for the generate-build-provenance action with containers

jobs:
  image:
    name: Build Image
    # TODO: Switch to openchami tag once tagged
    uses: OpenCHAMI/github-actions/.github/workflows/docker-build-release.yml@45c9f0fd834c1b0e5a3eb6509e22c25faa05f686
    with:
      fetch-depth: 1
      registry-name: ghcr.io/rainest/kubevirtbmc
      platforms: "linux/amd64,linux/arm64"
      docker-file: "Dockerfile"
